Add pacmd set-sink wrapper module
albertlauncher/python pull request #130
Opened 2022-08-10 07:06 UTC by c4pQ

2022-10-08 10:39 UTC, ManuelSchneid3r requested changes

2022-10-08 10:39 UTC, ManuelSchneid3r commented on pacmd/__init__.py
> +__title__ = "Pulseaudio cmd"
no need for the "cmd"

2022-10-08 10:39 UTC, ManuelSchneid3r commented on pacmd/__init__.py
> +__triggers__ = "pacmd "
i'd tend to use just pa

2022-10-08 10:39 UTC, ManuelSchneid3r commented on pacmd/__init__.py
> +iconPath = iconLookup('audio-headphones')
see https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/pulseaudio-text.svg i dunno if we can expect that 'pulseaudio-text' is on every system but id rather use this one

2022-10-08 10:41 UTC, ManuelSchneid3r commented
Neat. But i dont see the need to be to narrow. This is basically a PA wrapper. I dont expect you to wrap the entire api. This could serve as a starting point for others who need futher functionality.

2022-10-18 13:34 UTC, c4pQ commented on pacmd/__init__.py
> +__title__ = "Pulseaudio cmd"
removed

2022-10-18 13:34 UTC, c4pQ commented on pacmd/__init__.py
> +__triggers__ = "pacmd "
makes sense

2022-10-19 07:28 UTC, c4pQ commented
Added requested changes

2023-01-03 19:35 UTC, ManuelSchneid3r commented
0.18 is out. please check the new api https://github.com/albertlauncher/plugins/blob/master/python/README.md

2023-03-29 16:47 UTC, ManuelSchneid3r commented
@c4pQ are you still interested in getting this plugin upstream?

2023-03-30 09:22 UTC, ManuelSchneid3r commented
I'll close this one due to the conflicts. Note that this has no further implication for me but to be able to work with the PR section in this repo efficiently. It is quite exhausting to keep track of the few active PRs between dozens of stale PRs. Please reopen or open a new PR if you are ready to merge.

2023-03-30 09:22 UTC, closed without merging