VPN bump to 0.5
albertlauncher/python pull request #155
Opened 2023-01-14 17:13 UTC by Bierchermuesli

i forked the vpn plugin in a dedicated branch - I think this would be ready to merge

2023-01-16 10:25 UTC, roman-acumen commented
its the same as #154 right?

2023-01-24 22:57 UTC, ManuelSchneid3r commented
Yes please and call these nm, network manager or something that makes it clear that nm is used. Otherwise it will work expectation when ppl use sth else. Imho the name should represent the scope. Vpn narrows the nm scope (whatever one could imagine manipulating interfaces printing net things) while not being complete in the sense that it does not interface other von providers.

2023-01-25 16:28 UTC, ManuelSchneid3r requested changes

2023-01-25 16:28 UTC, ManuelSchneid3r commented on vpn/__init__.py
> +
this text will apear in the setings dialog. please use it only if it is beneficial for users. title is in the config and will be duplicated.

2023-01-25 16:28 UTC, ManuelSchneid3r commented on vpn/__init__.py
> +md_version = "0.5"
__version__ = "0.4.0" was iidmajor.iidminor.version there fore 1.1 makes sene i guess

2023-01-25 16:28 UTC, ManuelSchneid3r commented on vpn/__init__.py
> +md_id = "vpn"
you can drop this it will automatically be set to the dir name

2023-01-25 16:28 UTC, ManuelSchneid3r commented on vpn/__init__.py
> +md_description = "Manages VPN (via nmcli)"
Please from the user POV "Manage VPN…

2023-01-25 16:28 UTC, ManuelSchneid3r commented on vpn/__init__.py
> +md_authors = ["@janeklb"]
this field does not exist

2023-01-25 16:28 UTC, ManuelSchneid3r commented on vpn/__init__.py
> +md_lib_dependencies = ["nmcli"]
is this really this one https://pypi.org/project/nmcli/ ? important otherwise dep mgmt will not work

2023-01-25 16:28 UTC, ManuelSchneid3r commented on vpn/__init__.py
> +md_lib_dependencies = ["nmcli"]
wait it does not even use this package. use `md_bin_dependencies`

2023-01-31 09:23 UTC, merged