feat(vscode_projects): add vscode project plugin
albertlauncher/python pull request #161
Opened 2023-02-11 01:22 UTC by cathaysia

Signed-off-by: Longtao Zhang <DragonBillow@outlook.com>

2023-02-11 08:21 UTC, ManuelSchneid3r requested changes
This plugin is far from polished. Being in this unfinished state, why do you send this PR at all? Do you really expect me to merge and ship it? Please polish, otherwise i cant merge it.

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +This extension provides a quick introduction on how to use the new Python pluging interface.
this string appears in the settings and should serve as longer description of the plugin

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +md_version = "1.1"
has there been a 1.0?

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +md_description = "vscode projects"
This is a human readable pretty printed string. i should be brief and imperative like "Open VSCode projects"

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +md_name = "vscode projects"
This is a human readable pretty printed string. Use VSCode projects

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +md_url = "https://github.com/albertlauncher/python/tree/master/kill"
no not kill

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +vsc_db = "~/.config/Code/User/globalStorage/state.vscdb"
try to generalize this. this will work on linux only.

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +        return __name__
use md_id here

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +    def initialize(self):
drop if unused

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +                                    "打开",
?! this should be usable for the entire worldwide community

2023-02-11 08:21 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +                                    "使用 vscode 打开项目",
same here

2023-02-12 12:27 UTC, cathaysia commented
OK, I give some changes on codes

2023-02-16 08:20 UTC, ManuelSchneid3r requested changes

2023-02-16 08:20 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
>          return md_iid
iid is the interface identifier. Use md_id

2023-02-19 12:25 UTC, ManuelSchneid3r commented on vscode_projects/__init__.py
> +                        id=md_id,
this should be the identifier of a project item right? identifiers have to be unique.

2023-02-20 07:45 UTC, ManuelSchneid3r reviewed
I think you got that wrong. The identifier has to be unique such that each item has its own idententifier, use project ids or path or the name of the project (but actually this is probably not guaranteed to be unique as well)

2023-02-21 06:06 UTC, cathaysia commented
> I think you got that wrong. The identifier has to be unique such that each item has its own idententifier, use project ids or path or the name of the project (but actually this is probably not guaranteed to be unique as well)

can I use uuid.uuid1() ?

2023-02-22 07:27 UTC, closed without merging

2023-02-23 12:49 UTC, ManuelSchneid3r commented
@cathaysia why did you close the pr? 

> can I use uuid.uuid1() ?

why not just sth like `'md_id' + project_path`?

The id has to be persistant (because it will be reused for sorting) and unique (because it is used as icon cache key).

2023-02-26 02:44 UTC, cathaysia commented
I worry that I don't have much time to maintain this code. This plugin was originally written just because I needed this plugin. If someone is happy to maintain it, you can simply copy and modify my code.

2023-03-06 09:50 UTC, ManuelSchneid3r commented
You dont necessarily have to maintain it. Its fine to leave the maintainer field empty, but initially the plugin should be polished before its shipped around the world.