Fix that plugin returned no results if recentProjects.xml is missing
albertlauncher/python pull request #183
Opened 2023-08-20 14:10 UTC by poettig

If an IDE is installed, but there is no recentProjects.xml, `ElementTree.parse` threw an uncaught FileNotFoundError, causing a critical albert error.

```
Invoked with: 
16:05:01 [crit:python] FileNotFoundError: [Errno 2] No such file or directory: '/home/<redacted>/.config/JetBrains/Rider2021.3/options/recentProjects.xml'

At:
  /usr/lib/python3.11/xml/etree/ElementTree.py(569): parse
  /usr/lib/python3.11/xml/etree/ElementTree.py(1218): parse
  /usr/share/albert/python/plugins/jetbrains_projects/__init__.py(81): _parse_recent_projects
  /usr/share/albert/python/plugins/jetbrains_projects/__init__.py(62): list_projects
  /usr/share/albert/python/plugins/jetbrains_projects/__init__.py(164): handleTriggerQuery

2023-08-21 07:17 UTC, tomsquest requested changes
Hi @poettig ,

Thanks for your PR.

I would have fixed that by changing the `except ElementTree.ParseError:` to be more relax.
Indeed this line should also catch and handle the missing file.

Can you update your PR?

Also, there are some formatting and `@staticmethod` changes.

2023-08-23 06:59 UTC, tomsquest commented
Hi @poettig great one! Thanks for the improvement.

@ManuelSchneid3r Good to merge for me.

2023-08-23 06:59 UTC, tomsquest approved these changes

2023-08-23 07:25 UTC, merged

2023-08-23 07:40 UTC, ManuelSchneid3r commented
👍